org: lfedge
image: eve-node-exporter
config:
  binds:
    - /:/hostfs:ro,rslave
    - /proc:/hostfs/proc
    - /sys:/hostfs/sys
    - /persist:/persist
  net: host
  pid: host
  capabilities:
    - all
  devices: