name: PR Approval Runner   # secrets-enabled stage
on:
  workflow_run:
    workflows: ["PR Approval Gate"]
    types: [completed]

jobs:
  context:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      pr:     ${{ steps.parse.outputs.pr }}
      run_id: ${{ steps.parse.outputs.run_id }}

    steps:
      - name: Download Gate context
        uses: actions/download-artifact@v4
        with:
          name: gate-context
          run-id: ${{ github.event.workflow_run.id }}   # isolate to this Gate run
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: parse
        run: |
          PR=$(jq -r '.pr'  gate-context.json)
          RUN=$(jq -r '.run' gate-context.json)
          echo "pr=$PR"       >> "$GITHUB_OUTPUT"
          echo "run_id=$RUN"  >> "$GITHUB_OUTPUT"

  test_suite_pr:
    uses: lf-edge/eden/.github/workflows/test.yml@1.0.2
    needs: context
    secrets: inherit
    if: ${{ needs.context.outputs.pr != '' }}             # extra guard
    strategy:
      fail-fast: false
      matrix:
        arch:     [amd64]
        hv:       [kvm]
        platform: ["generic"]

    with:
      eve_image:         "evebuild/pr:${{ needs.context.outputs.pr }}"
      eve_log_level:     "debug"
      eve_artifact_name: "eve-${{ matrix.hv }}-${{ matrix.arch }}-${{ matrix.platform }}"
      artifact_run_id:   ${{ needs.context.outputs.run_id }}
      eden_version:      "1.0.2"
