# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025, Zededa, Inc.
---
name: Rerun CI

on:  # yamllint disable-line rule:truthy
  issue_comment:
    types: [created]

jobs:
  rerun-workflows:
    if: |
      github.event.issue.pull_request && startsWith(github.event.comment.body, '/rerun')
    runs-on: ubuntu-latest

    permissions:
      actions: write
      issues: read
      pull-requests: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse CODEOWNERS to get allowed users
        run: |
          CODEOWNERS=".github/CODEOWNERS"
          awk '{for(i=1;i<=NF;i++) if($i ~ /^@/) print substr($i,2)}' "$CODEOWNERS" | sort -u > allowed_users.txt

      - name: Check if comment author is allowed
        run: |
          COMMENT_USER="${{ github.event.comment.user.login }}"
          echo "User: $COMMENT_USER"
          if ! grep -Fxq "$COMMENT_USER" allowed_users.txt; then
            echo "User $COMMENT_USER is not allowed to rerun CI." >&2
            exit 1
          fi

      - name: Set run mode (red or yellow)
        id: mode
        run: |
          BODY="${{ github.event.comment.body }}"
          if [[ "$BODY" =~ ^/rerun[[:space:]]+yellow ]]; then
            echo "mode=yellow" >> $GITHUB_OUTPUT
          elif [[ "$BODY" =~ ^/rerun[[:space:]]+red ]]; then
            echo "mode=red" >> $GITHUB_OUTPUT
          else
            echo "Unknown rerun mode" >&2
            exit 1
          fi

      - name: Gather PR branch and SHA
        id: prinfo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.issue.number }}"
          REPO="${{ github.repository }}"

          BRANCH=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json headRefName -q .headRefName)
          SHA=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json headRefOid -q .headRefOid)
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Find and act on workflow runs for this PR's latest commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ steps.prinfo.outputs.sha }}
          REPO: ${{ github.repository }}
          MODE: ${{ steps.mode.outputs.mode }}
          GH_REPO: ${{ github.repository }}
        run: |
          set -euo pipefail

          # Fetch all workflow runs for this SHA
          echo "gh api /repos/$REPO/actions/runs | jq \".workflow_runs | map(select(.head_sha == \\\"$SHA\\\"))\""
          RUNS=$(gh api /repos/$REPO/actions/runs | jq ".workflow_runs | map(select(.head_sha == \"$SHA\"))")
          if [ -z "$RUNS" ]; then
            echo "No workflow runs found for SHA $SHA in repository $REPO"
            exit 0
          fi

          # Cancel in-progress or queued runs (yellow)
          if [[ "$MODE" == "yellow" ]]; then
            echo "$RUNS" | jq -r '.[] | select(.status != "completed") | .id' | while read -r run_id; do
              [ -z "$run_id" ] && continue
              echo "Canceling run $run_id"
              gh run cancel "$run_id" --repo "$REPO"
            done

            # Wait for all to finish canceling
            for i in {1..15}; do
              sleep $((i))
              RUNS_LEFT=$(gh api "/repos/$REPO/actions/runs?per_page=100" | jq "[.workflow_runs[] | select(.head_sha == env.SHA and .status != \"completed\")] | length")
              echo "Still running: $RUNS_LEFT"
              [ "$RUNS_LEFT" -eq 0 ] && break
            done

            # Refresh RUNS
            RUNS=$(gh api "/repos/$REPO/actions/runs?per_page=100" | jq ".workflow_runs | map(select(.head_sha == env.SHA))")
          fi

          # Rerun all failed/canceled/skipped runs (red)
          echo "$RUNS" | jq -r '.[] | select(.status == "completed" and (.conclusion != "success" and .conclusion != "skipped")) | .id' \
            | while read -r run_id; do
                [ -z "$run_id" ] && continue
                echo "Re-running failed/canceled run $run_id"
                gh run rerun "$run_id" --repo "$REPO"
              done
